# Generated by Django 6.0.3 on 2026-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_profilemodel_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='images',
            field=models.ImageField(default='images/img.jpg', upload_to='uploads/'),
        ),
    ]
