# Generated by Django 6.0.3 on 2026-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_taskmodel_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
